webtalk_init -webtalk_dir /home/krekker/spi_adc/spi_adc.sim/sim_1/behav/xsim/xsim.dir/tb_test_mcs3201_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 12 15:43:53 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2644227" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ea9647c8-8b98-49b9-988d-3ac168306c23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6e692bd9f0fc42efa65c714f5838c303" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 10 (buster)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1199.057 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "9.73_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2623520497 -regid "" -xml /home/krekker/spi_adc/spi_adc.sim/sim_1/behav/xsim/xsim.dir/tb_test_mcs3201_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/krekker/spi_adc/spi_adc.sim/sim_1/behav/xsim/xsim.dir/tb_test_mcs3201_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/krekker/spi_adc/spi_adc.sim/sim_1/behav/xsim/xsim.dir/tb_test_mcs3201_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
