# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/physical_constr.xdc

# Block Designs: bd/linux_qmtech/linux_qmtech.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech || ORIG_REF_NAME==linux_qmtech} -quiet] -quiet

# IP: bd/linux_qmtech/ip/linux_qmtech_processing_system7_0_0/linux_qmtech_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech_processing_system7_0_0 || ORIG_REF_NAME==linux_qmtech_processing_system7_0_0} -quiet] -quiet

# IP: bd/linux_qmtech/ip/linux_qmtech_proc_sys_reset_0_0/linux_qmtech_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech_proc_sys_reset_0_0 || ORIG_REF_NAME==linux_qmtech_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/linux_qmtech/ip/linux_qmtech_axi_interconnect_0_0/linux_qmtech_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech_axi_interconnect_0_0 || ORIG_REF_NAME==linux_qmtech_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/linux_qmtech/ip/linux_qmtech_axi_gpio_0_1/linux_qmtech_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech_axi_gpio_0_1 || ORIG_REF_NAME==linux_qmtech_axi_gpio_0_1} -quiet] -quiet

# IP: bd/linux_qmtech/ip/linux_qmtech_auto_pc_0/linux_qmtech_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==linux_qmtech_auto_pc_0 || ORIG_REF_NAME==linux_qmtech_auto_pc_0} -quiet] -quiet

# XDC: bd/linux_qmtech/linux_qmtech_ooc.xdc
