#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 12 15:27:52 CET 2021
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6e692bd9f0fc42efa65c714f5838c303 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_test_mcs3201_behav xil_defaultlib.tb_test_mcs3201 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 6e692bd9f0fc42efa65c714f5838c303 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_test_mcs3201_behav xil_defaultlib.tb_test_mcs3201 xil_defaultlib.glbl -log elaborate.log

