#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 12 15:28:03 CET 2021
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_test_mcs3201_behav -key {Behavioral:sim_1:Functional:tb_test_mcs3201} -tclbatch tb_test_mcs3201.tcl -log simulate.log"
xsim tb_test_mcs3201_behav -key {Behavioral:sim_1:Functional:tb_test_mcs3201} -tclbatch tb_test_mcs3201.tcl -log simulate.log

