# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/krekker/linux_qmtech/linux_qmtech.srcs/sources_1/bd/linux_qmtech/ip/linux_qmtech_auto_pc_0/linux_qmtech_auto_pc_0.xci
# IP: The module: 'linux_qmtech_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krekker/linux_qmtech/linux_qmtech.srcs/sources_1/bd/linux_qmtech/ip/linux_qmtech_auto_pc_0/linux_qmtech_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'linux_qmtech_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/krekker/linux_qmtech/linux_qmtech.srcs/sources_1/bd/linux_qmtech/ip/linux_qmtech_auto_pc_0/linux_qmtech_auto_pc_0.xci
# IP: The module: 'linux_qmtech_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/krekker/linux_qmtech/linux_qmtech.srcs/sources_1/bd/linux_qmtech/ip/linux_qmtech_auto_pc_0/linux_qmtech_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'linux_qmtech_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
