set_property PACKAGE_PIN G15 [get_ports button]
set_property PACKAGE_PIN R2 [get_ports clk_i]
set_property PACKAGE_PIN H14 [get_ports i_rst]
set_property PACKAGE_PIN E18 [get_ports result]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst]
set_property IOSTANDARD LVCMOS33 [get_ports result]
